### ISSUE TITLE
Failed to load extension markdown_fenced_code_tabs

### ISSUE THREAD

**Issue by ZsharE** [yacir/markdown-fenced-code-tabs#22]
```
ERROR   -  Config value 'markdown_extensions': Failed to load extension 'markdown_fenced_code_tabs'.
             File "C:\Python\Python312\Lib\site-packages\mkdocs\config\config_options.py", line 1031, in run_validation
               md.registerExtensions((ext,), self.configdata)
             File "C:\Python\Python312\Lib\site-packages\markdown\core.py", line 181, in registerExtensions
               ext.extendMarkdown(self)
           TypeError: CodeTabsExtension.extendMarkdown() missing 1 required positional argument: 'md_globals'
```

Tested on markdown version: 3.6

**markdown_fenced_code_tabs works with markdown < 3.4**

**Comment by ZsharE** [comment]
Since the owner of this repository is not taking any action, I have created a new repository that will support markdown >= 3.4

https://github.com/elmahio/markdown-fenced-code-tabs-next
